SCREENH = 600
SCREENW = 640
LEFT = 0
RIGHT = 1
UP = 2
DOWN = 3
BLACK = (0, 0, 0)
EXTIMELAPSE = 250
BOSSHEALTH = 2000  # default 2000
PLAYERHEALTH = 3  # default 3

# speed of map scrolling
NORMSCROLLSPEED = 2
SCROLLSPEED = 2
MAXSCROLLSPEED = 8

# most saucers that can be in play before boss comes out
MAXENEMIES = 10

STATMOD_DURATION = 15   # seconds
MAX_SPEED = 20

PLAYERSPEED = 5
PLAYERMAXSPEED = 15